takehome_wh:
  outputs:
    dev:
      type: snowflake
      warehouse: takehome_wh
      database: takehome_db
      schema: takehome_schema
      threads: 2

      account: "{{ env_var('SNOWFLAKE_TAKEHOME_ACCOUNT') }}" 
      password: "{{ env_var('SNOWFLAKE_TAKEHOME_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TAKEHOME_ROLE') }}"
      user: "{{ env_var('SNOWFLAKE_TAKEHOME_USER') }}"
      
  target: dev
